"""Initial migration

Revision ID: 192f95bd85f8
Revises: 
Create Date: 2025-10-23 16:19:28.960459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '192f95bd85f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dishes',
    sa.Column('id', sa.Integer(), nullable=False, comment='用户id'),
    sa.Column('name', sa.String(), nullable=False, comment='用户名'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('dishes_pkey')),
    sa.UniqueConstraint('name', name=op.f('dishes_name_key'))
    )
    op.create_index(op.f('dishes_created_at_idx'), 'dishes', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('dishes_created_at_idx'), table_name='dishes')
    op.drop_table('dishes')
    # ### end Alembic commands ###
