"""add user and access_token table

Revision ID: 61cc931f88bb
Revises: bc361dc96c18
Create Date: 2025-10-28 17:38:56.789596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = '61cc931f88bb'
down_revision: Union[str, Sequence[str], None] = 'bc361dc96c18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    op.create_index(op.f('user_created_at_idx'), 'user', ['created_at'], unique=False)
    op.create_index(op.f('user_email_idx'), 'user', ['email'], unique=True)
    op.create_table('accesstoken',
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('token', sa.String(length=43), nullable=False),
    sa.Column('created_at', fastapi_users_db_sqlalchemy.generics.TIMESTAMPAware(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('accesstoken_user_id_fkey'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('token', name=op.f('accesstoken_pkey'))
    )
    op.create_index(op.f('accesstoken_created_at_idx'), 'accesstoken', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('accesstoken_created_at_idx'), table_name='accesstoken')
    op.drop_table('accesstoken')
    op.drop_index(op.f('user_email_idx'), table_name='user')
    op.drop_index(op.f('user_created_at_idx'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
